# Generated by Django 5.2.7 on 2025-10-23 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='Doce', max_length=100)),
                ('production_cost', models.DecimalField(decimal_places=2, help_text='Custo total de produção', max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, help_text='Preço de venda', max_digits=10)),
                ('yield_quantity', models.DecimalField(decimal_places=2, help_text='Quantidade produzida por lote', max_digits=10)),
                ('yield_unit', models.CharField(default='unidades', max_length=50)),
                ('calories_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('protein_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fat_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carbs_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Recipes',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='products.recipe')),
            ],
            options={
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
